global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: nethermind
    metrics_path: /metrics
    static_configs:
      - targets: 
        - nethermind:8008
  - job_name: lighthouse
    metrics_path: /metrics
    static_configs:
      - targets: 
        - lighthouse:5054
  - job_name: ssv
    metrics_path: /metrics
    static_configs:
      - targets:
        - ssv-node:15000
  - job_name: ssv_health
    metrics_path: /health
    static_configs:
      - targets:
        - ssv-node:15000
