{
 "title": "Operator Performance Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": "ssv-node" }
  ]
 },
 "panels": [
  { "title": "Operator Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Validator Status",
   "type": "timeseries",
   "description": "Total amount of validators and total active validators\n",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(ssv:validator:v2:status{instance=~\"$instance.*\"} == 3)",
     "legendFormat": "Active"
    },
    {
     "expr": "count(ssv:validator:v2:status{instance=~\"$instance.*\"} != 9)",
     "legendFormat": "Total"
    },
    {
     "expr": "count(ssv:validator:v2:status{instance=~\"$instance.*\"} == 6)",
     "legendFormat": "Slashed"
    },
    {
     "expr": "count(ssv:validator:v2:status{instance=~\"$instance.*\"} == 9)",
     "legendFormat": "Removed"
    }
   ]
  },
  { "title": "Attester Role", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Instance Round Distribution ",
   "type": "bargauge",
   "description": "Amount of validators in a certain round number",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"ATTESTER\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"ATTESTER\"} > 1)",
     "legendFormat": "Round >1"
    },
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"ATTESTER\"} > 2)",
     "legendFormat": "Round >2"
    },
    {
     "expr": "count_values(\"round\", ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"ATTESTER\"})",
     "legendFormat": "Round {{ round }}"
    }
   ]
  },
  {
   "title": "Failed submissions",
   "type": "timeseries",
   "description": "Rate per second of failed submissions within last 5 minutes",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_roles_failed{instance=~\"$instance.*\", role=\"ATTESTER\"}[5m]))",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Submitted Roles",
   "type": "timeseries",
   "description": "Rate per second of successfully submitted roles within last 5 minutes",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_roles_submitted{instance=~\"$instance.*\", role=\"ATTESTER\"}[5m]))",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Duty Full Flow (Excl. Att. Data Req.) Duration",
   "type": "timeseries",
   "description": "Attestation full flow duration excluding waiting for 1/3 of slot time and attestation data request.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"ATTESTER\",le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"ATTESTER\",le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"ATTESTER\",le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"ATTESTER\",le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"ATTESTER\",le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Proposal Stage Duration",
   "type": "timeseries",
   "description": "Proposal stage duration for an attester role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"proposal\",instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"proposal\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"proposal\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"proposal\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"proposal\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"proposal\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"1.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"proposal\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 1.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"2.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"1.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"proposal\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1.5 - 2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"2.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"proposal\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "2 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"proposal\",le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"proposal\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Prepare Stage Duration",
   "type": "timeseries",
   "description": "Prepare stage duration for an attester role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"prepare\",instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"prepare\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"prepare\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"prepare\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"prepare\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"prepare\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"1.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"prepare\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 1.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"2.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"1.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"prepare\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1.5 - 2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"2.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"prepare\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "2 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"prepare\",le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"prepare\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Commit Stage Duration",
   "type": "timeseries",
   "description": "Commit stage duration for an attester role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"commit\",instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"commit\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"commit\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"commit\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"commit\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"commit\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"1.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"commit\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 1.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"2.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"1.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"commit\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1.5 - 2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"2.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"commit\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "2 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_instance_stage_duration_seconds_bucket{stage=\"commit\",le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_instance_stage_duration_seconds_count{stage=\"commit\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Consensus Duration",
   "type": "timeseries",
   "description": "Consensus duration for an attester role (duration from proposal to commits) broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Post-consensus (signature collection) Duration",
   "type": "timeseries",
   "description": "Post-Consensus duration for an attester role (signature collection duration) broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"ATTESTER\",le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Attestation Data Request Duration",
   "type": "timeseries",
   "description": "Attestation data request duration for an attester role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"ATTESTER\", le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"ATTESTER\", instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"ATTESTER\", le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"ATTESTER\", le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"ATTESTER\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"ATTESTER\", le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"ATTESTER\", le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"ATTESTER\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"ATTESTER\", le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"ATTESTER\", le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"ATTESTER\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"ATTESTER\", le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"ATTESTER\", le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"ATTESTER\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"ATTESTER\", le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"ATTESTER\", le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"ATTESTER\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"ATTESTER\", le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"ATTESTER\", le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"ATTESTER\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"ATTESTER\", le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"ATTESTER\", le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"ATTESTER\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Attestation Submission Duration",
   "type": "timeseries",
   "description": "Attestation submission duration for an attester role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(sssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"ATTESTER\",le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"ATTESTER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  { "title": "Proposer Role", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Instance Round Distribution ",
   "type": "bargauge",
   "description": "Amount of validators in a certain round number",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"PROPOSER\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"PROPOSER\"} > 1)",
     "legendFormat": "Round >1"
    },
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"PROPOSER\"} > 2)",
     "legendFormat": "Round >2"
    },
    {
     "expr": "count_values(\"round\", ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"PROPOSER\"})",
     "legendFormat": "Round {{ round }}"
    }
   ]
  },
  {
   "title": "Failed submissions",
   "type": "timeseries",
   "description": "Rate per second of failed submissions within last 5 minutes",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 54 },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_roles_failed{instance=~\"$instance.*\", role=\"PROPOSER\"}[5m]))",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Submitted Roles",
   "type": "timeseries",
   "description": "Rate per second of successfully submitted roles within last 5 minutes",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 54 },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_roles_submitted{instance=~\"$instance.*\", role=\"PROPOSER\"}[5m]))",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Duty Full Flow Duration",
   "type": "timeseries",
   "description": "Duty full flow duration for a proposer role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"PROPOSER\",le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"PROPOSER\",le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"PROPOSER\",le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"PROPOSER\",le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"PROPOSER\",le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Beacon Block Request Duration",
   "type": "timeseries",
   "description": "Beacon block request duration for a proposer role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"PROPOSER\", le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"PROPOSER\", instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"PROPOSER\", le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"PROPOSER\", le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"PROPOSER\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"PROPOSER\", le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"PROPOSER\", le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"PROPOSER\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"PROPOSER\", le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"PROPOSER\", le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"PROPOSER\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"PROPOSER\", le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"PROPOSER\", le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"PROPOSER\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"PROPOSER\", le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"PROPOSER\", le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"PROPOSER\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"PROPOSER\", le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"PROPOSER\", le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"PROPOSER\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"PROPOSER\", le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"PROPOSER\", le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"PROPOSER\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Block Submission Duration",
   "type": "timeseries",
   "description": "Block submission duration for a proposer role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(sssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"PROPOSER\",le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Pre-consensus Duration",
   "type": "timeseries",
   "description": "Pre-Consensus duration for a proposer role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Consensus Duration",
   "type": "timeseries",
   "description": "Consensus duration for a proposer role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Post-consensus Duration",
   "type": "timeseries",
   "description": "Post-Consensus duration for a proposer role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"PROPOSER\",le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"PROPOSER\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  { "title": "Aggregator Role", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Instance Round Distribution ",
   "type": "bargauge",
   "description": "Amount of validators in a certain round number",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 89 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"AGGREGATOR\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"AGGREGATOR\"} > 1)",
     "legendFormat": "Round >1"
    },
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"AGGREGATOR\"} > 2)",
     "legendFormat": "Round >2"
    },
    {
     "expr": "count_values(\"round\", ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"AGGREGATOR\"})",
     "legendFormat": "Round {{ round }}"
    }
   ]
  },
  {
   "title": "Failed submissions",
   "type": "timeseries",
   "description": "Rate per second of failed submissions within last 5 minutes",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 89 },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_roles_failed{instance=~\"$instance.*\", role=\"AGGREGATOR\"}[5m]))",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Submitted Roles",
   "type": "timeseries",
   "description": "Rate per second of successfully submitted roles within last 5 minutes",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 89 },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_roles_submitted{instance=~\"$instance.*\", role=\"AGGREGATOR\"}[5m]))",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Duty Full Flow (Excl. Att. Data & Agg. Attestation Req.) Duration",
   "type": "timeseries",
   "description": "Duty full flow duration for an aggregator role excluding waiting for 2/3 of slot time, attestation data and aggregate attestation requests.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Aggregate Attestation Request Duration",
   "type": "timeseries",
   "description": "Aggregate attestation request duration for an aggregator role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"AGGREGATOR\", le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"AGGREGATOR\", instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"AGGREGATOR\", le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"AGGREGATOR\", le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"AGGREGATOR\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"AGGREGATOR\", le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"AGGREGATOR\", le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"AGGREGATOR\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"AGGREGATOR\", le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"AGGREGATOR\", le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"AGGREGATOR\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"AGGREGATOR\", le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"AGGREGATOR\", le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"AGGREGATOR\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"AGGREGATOR\", le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"AGGREGATOR\", le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"AGGREGATOR\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"AGGREGATOR\", le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"AGGREGATOR\", le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"AGGREGATOR\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"AGGREGATOR\", le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"AGGREGATOR\", le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"AGGREGATOR\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Proof Submission Duration",
   "type": "timeseries",
   "description": "Proof submission duration for an aggregator role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(sssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Pre-consensus Duration",
   "type": "timeseries",
   "description": "Pre-Consensus duration for an aggregator role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Consensus Duration",
   "type": "timeseries",
   "description": "Consensus duration for an aggregator role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Post-consensus Duration",
   "type": "timeseries",
   "description": "Post-Consensus duration for an aggregator role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"AGGREGATOR\",le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"AGGREGATOR\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  { "title": "Sync Committee Role", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 } },
  {
   "title": "Instance Round Distribution ",
   "type": "bargauge",
   "description": "Amount of validators in a certain round number",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 124 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"SYNC_COMMITTEE\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"SYNC_COMMITTEE\"} > 1)",
     "legendFormat": "Round >1"
    },
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"SYNC_COMMITTEE\"} > 2)",
     "legendFormat": "Round >2"
    },
    {
     "expr": "count_values(\"round\", ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"SYNC_COMMITTEE\"})",
     "legendFormat": "Round {{ round }}"
    }
   ]
  },
  {
   "title": "Failed submissions",
   "type": "timeseries",
   "description": "Rate per second of failed submissions within last 5 minutes",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 124 },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_roles_failed{instance=~\"$instance.*\", role=\"SYNC_COMMITTEE\"}[5m]))",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Submitted Roles",
   "type": "timeseries",
   "description": "Rate per second of successfully submitted roles within last 5 minutes",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 124 },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_roles_submitted{instance=~\"$instance.*\", role=\"SYNC_COMMITTEE\"}[5m]))",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Duty Full Flow (Excl. Beacon Block Root Req.) Duration",
   "type": "timeseries",
   "description": "Duty full flow duration for a sync committee role  excluding waiting for 1/3 of slot time and beacon block root request..  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Beacon Block Root Request Duration",
   "type": "timeseries",
   "description": "Beacon block root request duration for a sync committee role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"SYNC_COMMITTEE\", le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"SYNC_COMMITTEE\", instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"SYNC_COMMITTEE\", le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"SYNC_COMMITTEE\", le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"SYNC_COMMITTEE\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"SYNC_COMMITTEE\", le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"SYNC_COMMITTEE\", le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"SYNC_COMMITTEE\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"SYNC_COMMITTEE\", le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"SYNC_COMMITTEE\", le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"SYNC_COMMITTEE\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"SYNC_COMMITTEE\", le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"SYNC_COMMITTEE\", le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"SYNC_COMMITTEE\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"SYNC_COMMITTEE\", le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"SYNC_COMMITTEE\", le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"SYNC_COMMITTEE\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"SYNC_COMMITTEE\", le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"SYNC_COMMITTEE\", le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"SYNC_COMMITTEE\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"SYNC_COMMITTEE\", le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"SYNC_COMMITTEE\", le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"SYNC_COMMITTEE\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Sync Message Submission Duration",
   "type": "timeseries",
   "description": "Sync Message submission duration for a sync committee role. Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(sssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Consensus Duration",
   "type": "timeseries",
   "description": "Consensus duration for a sync committee role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Post-consensus Duration",
   "type": "timeseries",
   "description": "Post-Consensus duration for a sync committee role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE\",le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  { "title": "Sync Committee Aggregator Role", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 158 } },
  {
   "title": "Instance Round Distribution ",
   "type": "bargauge",
   "description": "Amount of validators in a certain round number",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 159 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"SYNC_COMMITTEE_CONTRIBUTION\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"SYNC_COMMITTEE_CONTRIBUTION\"} > 1)",
     "legendFormat": "Round >1"
    },
    {
     "expr": "count(ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"SYNC_COMMITTEE_CONTRIBUTION\"} > 2)",
     "legendFormat": "Round >2"
    },
    {
     "expr": "count_values(\"round\", ssv_qbft_instance_round{instance=~\"$instance.*\", roleType=\"SYNC_COMMITTEE_CONTRIBUTION\"})",
     "legendFormat": "Round {{ round }}"
    }
   ]
  },
  {
   "title": "Failed submissions",
   "type": "timeseries",
   "description": "Rate per second of failed submissions within last 5 minutes",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 159 },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_roles_failed{instance=~\"$instance.*\", role=\"SYNC_COMMITTEE_CONTRIBUTION\"}[5m]))",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Submitted Roles",
   "type": "timeseries",
   "description": "Rate per second of successfully submitted roles within last 5 minutes",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 159 },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_roles_submitted{instance=~\"$instance.*\", role=\"SYNC_COMMITTEE_CONTRIBUTION\"}[5m]))",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Duty Full Flow (Excl. Beacon Block Root & Sync Comm. Contrib. Req.) Duration",
   "type": "timeseries",
   "description": "Duty full flow duration for a sync committee aggregator role excluding waiting for slot time,  beacon block root and sync committee contribution requests.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_duty_full_flow_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_duty_full_flow_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Sync Committee Contribution Request Duration",
   "type": "timeseries",
   "description": "Sync committee contribution request duration for a sync committee aggregator role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\", le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\", instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\", le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\", le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\", le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\", le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\", le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\", le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\", le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\", le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\", le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\", le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\", le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\", le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\", le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_beacon_data_request_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\", le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_beacon_data_request_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\", instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Signed Contribution And Proof Submission Duration",
   "type": "timeseries",
   "description": "Signed contribution and proof submission duration for a sync committee aggregator role. Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(sssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_beacon_submission_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_beacon_submission_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Pre-consensus Duration",
   "type": "timeseries",
   "description": "Pre-Consensus duration for a sync committee aggregator role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_pre_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Consensus Duration",
   "type": "timeseries",
   "description": "Consensus duration for a sync committee aggregator role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  },
  {
   "title": "Post-consensus Duration",
   "type": "timeseries",
   "description": "Post-Consensus duration for a sync committee aggregator role.  Broken down by seconds used then shown as a distributed percentage.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.02\",instance=~\"$instance.*\"}[5m])) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "< 0.02 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.05\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.02\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.02 - 0.05 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.1\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.05\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.05 - 0.1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.2\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.1\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.1 - 0.2 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.5\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.2\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.2 - 0.5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"1.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"0.5\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "0.5 - 1 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"5.0\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"1.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "(sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"+Inf\",instance=~\"$instance.*\"}[5m])) - sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{role=\"SYNC_COMMITTEE_CONTRIBUTION\",le=\"5.0\",instance=~\"$instance.*\"}[5m]))) / ignoring (le) sum(rate(ssv_validator_post_consensus_duration_seconds_count{role=\"SYNC_COMMITTEE_CONTRIBUTION\",instance=~\"$instance.*\"}[5m]))\n",
     "legendFormat": "> 5 s"
    }
   ]
  }
 ]
}